version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: fernanda
      POSTGRES_PASSWORD: '121296'
      POSTGRES_DB: api_development
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./api
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./api:/app
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://fernanda:121296@db:5432/api_development
      REDIS_URL: redis://redis:6379/0

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data:

